/* Generated By:JavaCC: Do not edit this line. SparkParserConstants.java */
package com.chronomus.workflow.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SparkParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int WORKFLOW = 10;
  /** RegularExpression Id. */
  int DEFINE = 11;
  /** RegularExpression Id. */
  int JOB = 12;
  /** RegularExpression Id. */
  int LOAD_PROPERTIES = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int MILLISECOND = 15;
  /** RegularExpression Id. */
  int SECOND = 16;
  /** RegularExpression Id. */
  int MINUTE = 17;
  /** RegularExpression Id. */
  int HOUR = 18;
  /** RegularExpression Id. */
  int DAY = 19;
  /** RegularExpression Id. */
  int WEEK = 20;
  /** RegularExpression Id. */
  int MONTH = 21;
  /** RegularExpression Id. */
  int YEAR = 22;
  /** RegularExpression Id. */
  int TODAY = 23;
  /** RegularExpression Id. */
  int NOW = 24;
  /** RegularExpression Id. */
  int DATE_LITERAL = 25;
  /** RegularExpression Id. */
  int NUMBER_LITERAL = 26;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 27;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 28;
  /** RegularExpression Id. */
  int HEX_LITERAL = 29;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 30;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 31;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 32;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 33;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 34;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 35;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 36;
  /** RegularExpression Id. */
  int STRING_LITERAL = 37;
  /** RegularExpression Id. */
  int IDENTIFIER = 38;
  /** RegularExpression Id. */
  int LETTER = 39;
  /** RegularExpression Id. */
  int PART_LETTER = 40;
  /** RegularExpression Id. */
  int LPAREN = 41;
  /** RegularExpression Id. */
  int RPAREN = 42;
  /** RegularExpression Id. */
  int LBRACE = 43;
  /** RegularExpression Id. */
  int RBRACE = 44;
  /** RegularExpression Id. */
  int LBRACKET = 45;
  /** RegularExpression Id. */
  int RBRACKET = 46;
  /** RegularExpression Id. */
  int SEMICOLON = 47;
  /** RegularExpression Id. */
  int COMMA = 48;
  /** RegularExpression Id. */
  int DOT = 49;
  /** RegularExpression Id. */
  int AT = 50;
  /** RegularExpression Id. */
  int ASSIGN = 51;
  /** RegularExpression Id. */
  int LT = 52;
  /** RegularExpression Id. */
  int BANG = 53;
  /** RegularExpression Id. */
  int TILDE = 54;
  /** RegularExpression Id. */
  int HOOK = 55;
  /** RegularExpression Id. */
  int COLON = 56;
  /** RegularExpression Id. */
  int EQ = 57;
  /** RegularExpression Id. */
  int LE = 58;
  /** RegularExpression Id. */
  int GE = 59;
  /** RegularExpression Id. */
  int NE = 60;
  /** RegularExpression Id. */
  int SC_OR = 61;
  /** RegularExpression Id. */
  int SC_AND = 62;
  /** RegularExpression Id. */
  int INCR = 63;
  /** RegularExpression Id. */
  int DECR = 64;
  /** RegularExpression Id. */
  int PLUS = 65;
  /** RegularExpression Id. */
  int MINUS = 66;
  /** RegularExpression Id. */
  int STAR = 67;
  /** RegularExpression Id. */
  int SLASH = 68;
  /** RegularExpression Id. */
  int BIT_AND = 69;
  /** RegularExpression Id. */
  int BIT_OR = 70;
  /** RegularExpression Id. */
  int XOR = 71;
  /** RegularExpression Id. */
  int REM = 72;
  /** RegularExpression Id. */
  int LSHIFT = 73;
  /** RegularExpression Id. */
  int PLUSASSIGN = 74;
  /** RegularExpression Id. */
  int MINUSASSIGN = 75;
  /** RegularExpression Id. */
  int STARASSIGN = 76;
  /** RegularExpression Id. */
  int SLASHASSIGN = 77;
  /** RegularExpression Id. */
  int ANDASSIGN = 78;
  /** RegularExpression Id. */
  int ORASSIGN = 79;
  /** RegularExpression Id. */
  int XORASSIGN = 80;
  /** RegularExpression Id. */
  int REMASSIGN = 81;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 82;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 83;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 84;
  /** RegularExpression Id. */
  int ELLIPSIS = 85;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"workflow\"",
    "\"def\"",
    "\"job\"",
    "\"loadProperties\"",
    "\"return\"",
    "\"millisecond\"",
    "\"second\"",
    "\"minute\"",
    "\"hour\"",
    "\"day\"",
    "\"week\"",
    "\"month\"",
    "\"year\"",
    "\"today\"",
    "\"now\"",
    "<DATE_LITERAL>",
    "<NUMBER_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"\\u001a\"",
  };

}
